FROM amazonlinux

RUN yum install -y \
        python3-pip \
	python3-devel\
        libgomp \
        mesa-libGL 
RUN yum groupinstall -y "Development Tools"
RUN python3 -m pip install --upgrade pip
ADD https://repo.anaconda.com/archive/Anaconda3-2021.04-Linux-aarch64.sh /root/anaconda.sh
RUN bash ~/anaconda.sh -b -p $HOME/anaconda
